services:

  db:
    image: postgres:12.20-alpine3.20
    container_name: postgres-area-poc
    shm_size: 128mb
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 5480:8080

  redis:
    image: redis:alpine
    restart: always
    container_name: area-redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data  # Persist Redis data between restarts
    env_file:
      - .env
    command: redis-server --save 60 1 --loglevel warning

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: area-backend
    container_name: server-area-poc
    env_file:
      - .env
    restart: always
    ports:
      - ${REST_API_PORT}:${REST_API_PORT}