# This CI is meant to execute frontend tests. It also checks/lints the code.

name: "AREA Frontend CI"

on:
  workflow_call:
    inputs:
      API_URL:
        description: "The API URL"
        required: true
        type: string

env:
  SERVER_API_URL: "${{ inputs.API_URL }}"
  CLIENT_API_URL: "${{ inputs.API_URL }}"

permissions: read-all

jobs:
  check:
    name: "Execute the ESLint checker, check code using SvelteKit and execute the tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: "Install NPM packages"
        run: "npm ci"

      - name: "Generate typesafe-i18n files"
        working-directory: "./apps/frontend/"
        run: "npm run i18n:ci"

      - name: "ESLint checker"
        working-directory: "./apps/frontend/"
        run: "npm run lint"

      - name: "Check code"
        working-directory: "./apps/frontend/"
        run: "npm run check"

      - name: "Build the project"
        working-directory: "./apps/frontend/"
        run: "npm run build"

#  cypress: TODO: fix Cypress in CI
#    name: "Cypress"
#    needs:
#      - "check"
#    uses: "./.github/workflows/ci-frontend-cypress.yml"
#    secrets: inherit
#    with:
#        API_URL: "${{ inputs.API_URL }}"

  build-docker-image:
    name: Building the Docker image
    runs-on: self-hosted
    needs:
      - check
    if: ${{ github.ref_name == 'main' || github.ref_name == 'frontend/dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ghcr.io/zowks/area-frontend:latest
