# This CI is meant to execute frontend tests. It also checks/lints the code.

name: "AREA Frontend CI"

on:
  workflow_call:

jobs:
  check:
    name: "Execute the ESLint checker, check code using SvelteKit and execute the tests"
    runs-on: "self-hosted"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: "Install NPM packages"
        working-directory: "./frontend/"
        run: "npm ci"

      - name: "Generate typesafe-i18n files"
        working-directory: "./frontend/"
        run: "npm run i18n:ci"

      - name: "ESLint checker"
        working-directory: "./frontend/"
        run: "npm run lint"

      - name: "Check code"
        working-directory: "./frontend/"
        run: "npm run check"

#      - name: "Execute Cypress tests"
#        working-directory: "./frontend/"
#        run: "npx start-server-and-test dev http://localhost:5173 cy:run"

      - name: "Build the project"
        working-directory: "./frontend/"
        run: "npm run build"

  cypress:
    name: "Cypress"
    needs:
      - "check"
    uses: "./.github/workflows/ci-frontend-cypress.yml"
