# This CI is meant to execute mobile tests. It also checks/lints the code.

name: "AREA Mobile CI"

on:
  workflow_call:
    inputs:
      API_URL:
        description: "The API URL"
        required: true
        type: string

env:
  EXPO_PUBLIC_API_URL: "${{ inputs.API_URL }}"

jobs:
  run-tests:
    name: "Execute the linter and execute the tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: "Install NPM packages"
        working-directory: "./mobile/"
        run: "npm ci"

      - name: "ESLint checker"
        working-directory: "./mobile/"
        run: "npm run lint"

      - name: "Tests execution"
        working-directory: "./mobile/"
        run: "npm run test"

  build:
    name: "Building the Android APK"
    runs-on: "ubuntu-latest"
    needs:
      - "run-tests"
    if: "${{ github.ref_name == 'main' || github.ref_name == 'common/dev' || github.ref_name == 'mobile/dev' }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: "Setup EAS"
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-cache: true
          packager: "npm"
          token: ${{ secrets.EXPO_TOKEN }}

      - name: "Install NPM packages"
        working-directory: "./mobile/"
        run: "npm ci"

      - name: "Build APK"
        working-directory: "./mobile/"
        run: eas build --non-interactive --platform=android
