# This CI is meant to execute the backend, frontend, mobile and common ones.
# If they are all successful, the repository is mirrored to the Epitech one
# (only if the workflow runs on main).

name: "AREA CI"

on:
  push:

jobs:
  common:
    name: "Common"
    uses: "./.github/workflows/ci-common.yml"

  backend:
    name: "Backend"
    needs:
      - "common"
    if: "${{ github.ref_name == 'main' || github.ref_name == 'common/dev' || startsWith(github.ref_name, 'backend/') }}"
    uses: "./.github/workflows/ci-backend.yml"
    permissions: write-all
    secrets: inherit

  frontend:
    name: "Frontend"
    needs:
      - "common"
    if: "${{ github.ref_name == 'main' || github.ref_name == 'common/dev' || startsWith(github.ref_name, 'frontend/') }}"
    uses: "./.github/workflows/ci-frontend.yml"
    permissions: read-all
    secrets: inherit
    with:
        API_URL: "https://api-area.zowks.fr"

  mobile:
    name: "Mobile"
    needs:
      - "common"
    if: "${{ github.ref_name == 'main' || github.ref_name == 'common/dev' || startsWith(github.ref_name, 'mobile/') }}"
    uses: "./.github/workflows/ci-mobile.yml"
    secrets: inherit
    with:
        API_URL: "https://api-area.zowks.fr"
        NODE_ENV: "production"
        FRONTEND_URL: "https://area.zowks.fr"

  mirror:
    name: "Mirror the refs to the Epitech repository"
    runs-on: "ubuntu-latest"
    needs:
      - "backend"
      - "frontend"
      - "mobile"
    if: "${{ github.ref_name == 'main' }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Mirror"
        uses: "pixta-dev/repository-mirroring-action@v1.1.1"
        with:
          target_repo_url: "${{ vars.MIRROR_URL }}"
          ssh_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"
